openapi: 3.0.3
info:
  title: Super Sport Car
  description: The OpenApi Spec for the BE and FE
  version: 1.0.0
servers:
  - url: 'https://localhost:8080'
paths:
  /v1/cars:
    get:
      tags:
        - car
      summary: Get all cars
      description: Get all cars
      operationId: getAllCars
      parameters:
        - name: make
          in: query
          description: vehicle manufacturer (e.g. audi or toyota)
          required: false
          schema:
            type: string
            default: "-"
        - name: model
          in: query
          description: vehicle model (e.g. a4 or corolla)
          required: false
          schema:
              type: string
              default: "-"
        - name: fuel_type
          in: query
          description: "type of fuel used. Possible values: gas, diesel, electricity"
          required: false
          schema:
              type: string
              default: "-"
        - name: drive
          in: query
          description: "drive transmission. Possible values: fwd (front-wheel drive), rwd (rear-wheel drive), awd (all-wheel drive), 4wd (four-wheel drive)."
          required: false
          schema:
              type: string
              default: "-"
        - name: cylinders
          in: query
          description: "number of cylinders in engine"
          required: false
          schema:
              type: integer
              default: 0
        - name: transmission
          in: query
          description: "type of transmission. Possible values: m (manual), a (automatic)"
          required: false
          schema:
              type: string
              default: "-"
        - name: year
          in: query
          description: "year of production"
          required: false
          schema:
              type: integer
              default: 0
        - name: min_city_kpl
          in: query
          description: "minimum city fuel consumption (kilometers per liter)"
          required: false
          schema:
              type: number
              default: 0
        - name: max_city_kpl
          in: query
          description: "maximum city fuel consumption (kilometers per liter)"
          required: false
          schema:
              type: number
              default: 0
        - name: min_highway_kpl
          in: query
          description: "minimum highway fuel consumption (kilometers per liter)"
          required: false
          schema:
              type: number
              default: 0
        - name: max_highway_kpl
          in: query
          description: "maximum highway fuel consumption (kilometers per liter)"
          required: false
          schema:
              type: number
              default: 0
        - name: min_comb_kpl
          in: query
          description: "minimum combined fuel consumption (kilometers per liter)"
          required: false
          schema:
              type: number
              default: 0
        - name: max_comb_kpl
          in: query
          description: "maximum combined fuel consumption (kilometers per liter)"
          required: false
          schema:
              type: number
              default: 0
        - name: limit
          in: query
          description: "maximum number of results"
          required: false
          schema:
              type: integer
              default: 5
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/car'
        '404':
          description: Cars not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '500':
          description: Critical server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

components:
  schemas:
    car:
      type: object
      properties:
        id:
          type: number
          format: int32
          example: 1
        city_kpl:
          type: number
          format: int32
          example: 1
        class:
          type: string
          example: midsize car
        combination_kpl:
          type: number
          format: int32
          example: 1
        cylinders:
          type: number
          format: int32
          example: 4
        displacement:
          type: number
          format: float
          example: 2.2
        drive:
          type: string
          example: fwd
        fuel_type:
          type: string
          example: gas
        highway_kpl:
          type: number
          format: int32
          example: 1
        make:
          type: string
          example: toyota
        model:
          type: string
          example: camry
        transmission:
          type: string
          example: a
        year:
          type: number
          format: int32
          example: 2012
    errorResponse:
      type: object
      properties:
        code:
          type: number
          format: int32
          example: 404
        message:
          type: string
          example: Car not found